// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCollection(arg1) {
  return window['go']['storage']['DesktopStorage']['AddCollection'](arg1);
}

export function AddDraft(arg1) {
  return window['go']['storage']['DesktopStorage']['AddDraft'](arg1);
}

export function AddDraftFromRequest(arg1, arg2) {
  return window['go']['storage']['DesktopStorage']['AddDraftFromRequest'](arg1, arg2);
}

export function AddEnvironment(arg1) {
  return window['go']['storage']['DesktopStorage']['AddEnvironment'](arg1);
}

export function AddEnvironmentDraft(arg1) {
  return window['go']['storage']['DesktopStorage']['AddEnvironmentDraft'](arg1);
}

export function AddFreshDraft(arg1) {
  return window['go']['storage']['DesktopStorage']['AddFreshDraft'](arg1);
}

export function AddFreshEnvDraft(arg1) {
  return window['go']['storage']['DesktopStorage']['AddFreshEnvDraft'](arg1);
}

export function AddReqExample(arg1, arg2) {
  return window['go']['storage']['DesktopStorage']['AddReqExample'](arg1, arg2);
}

export function ChooseFile() {
  return window['go']['storage']['DesktopStorage']['ChooseFile']();
}

export function ClearCollection(arg1) {
  return window['go']['storage']['DesktopStorage']['ClearCollection'](arg1);
}

export function CopyEnvironment(arg1, arg2) {
  return window['go']['storage']['DesktopStorage']['CopyEnvironment'](arg1, arg2);
}

export function CopyMockWithId(arg1) {
  return window['go']['storage']['DesktopStorage']['CopyMockWithId'](arg1);
}

export function CreateAndStartMockServer(arg1) {
  return window['go']['storage']['DesktopStorage']['CreateAndStartMockServer'](arg1);
}

export function CreateFreshMockDraft(arg1) {
  return window['go']['storage']['DesktopStorage']['CreateFreshMockDraft'](arg1);
}

export function CreateMockDraftFromMock(arg1, arg2) {
  return window['go']['storage']['DesktopStorage']['CreateMockDraftFromMock'](arg1, arg2);
}

export function CreateMockFromExample(arg1, arg2) {
  return window['go']['storage']['DesktopStorage']['CreateMockFromExample'](arg1, arg2);
}

export function CreateWorkspace(arg1) {
  return window['go']['storage']['DesktopStorage']['CreateWorkspace'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['storage']['DesktopStorage']['DeleteCollection'](arg1);
}

export function DeleteEnvDraftsUnderEnv(arg1) {
  return window['go']['storage']['DesktopStorage']['DeleteEnvDraftsUnderEnv'](arg1);
}

export function DeleteMockById(arg1) {
  return window['go']['storage']['DesktopStorage']['DeleteMockById'](arg1);
}

export function DeleteMockDraftById(arg1) {
  return window['go']['storage']['DesktopStorage']['DeleteMockDraftById'](arg1);
}

export function DeleteMockServer(arg1) {
  return window['go']['storage']['DesktopStorage']['DeleteMockServer'](arg1);
}

export function DeleteReqExample(arg1) {
  return window['go']['storage']['DesktopStorage']['DeleteReqExample'](arg1);
}

export function DeleteSavedReq(arg1) {
  return window['go']['storage']['DesktopStorage']['DeleteSavedReq'](arg1);
}

export function DownloadResponseFile(arg1) {
  return window['go']['storage']['DesktopStorage']['DownloadResponseFile'](arg1);
}

export function FindDraftById(arg1) {
  return window['go']['storage']['DesktopStorage']['FindDraftById'](arg1);
}

export function FindEnvDraft(arg1) {
  return window['go']['storage']['DesktopStorage']['FindEnvDraft'](arg1);
}

export function GetAllCollections(arg1) {
  return window['go']['storage']['DesktopStorage']['GetAllCollections'](arg1);
}

export function GetAllWorkspaces() {
  return window['go']['storage']['DesktopStorage']['GetAllWorkspaces']();
}

export function GetCollectionById(arg1) {
  return window['go']['storage']['DesktopStorage']['GetCollectionById'](arg1);
}

export function GetEnvironments(arg1) {
  return window['go']['storage']['DesktopStorage']['GetEnvironments'](arg1);
}

export function GetMockById(arg1) {
  return window['go']['storage']['DesktopStorage']['GetMockById'](arg1);
}

export function GetMockDraftById(arg1) {
  return window['go']['storage']['DesktopStorage']['GetMockDraftById'](arg1);
}

export function GetMocks(arg1) {
  return window['go']['storage']['DesktopStorage']['GetMocks'](arg1);
}

export function GetReqExampleById(arg1) {
  return window['go']['storage']['DesktopStorage']['GetReqExampleById'](arg1);
}

export function GetReqExamples(arg1) {
  return window['go']['storage']['DesktopStorage']['GetReqExamples'](arg1);
}

export function GetSavedRequestById(arg1) {
  return window['go']['storage']['DesktopStorage']['GetSavedRequestById'](arg1);
}

export function GetSavedRequests(arg1) {
  return window['go']['storage']['DesktopStorage']['GetSavedRequests'](arg1);
}

export function GetUIState() {
  return window['go']['storage']['DesktopStorage']['GetUIState']();
}

export function GetWorkspaceById(arg1) {
  return window['go']['storage']['DesktopStorage']['GetWorkspaceById'](arg1);
}

export function RemoveDraft(arg1) {
  return window['go']['storage']['DesktopStorage']['RemoveDraft'](arg1);
}

export function RemoveEnv(arg1) {
  return window['go']['storage']['DesktopStorage']['RemoveEnv'](arg1);
}

export function RemoveEnvDraft(arg1) {
  return window['go']['storage']['DesktopStorage']['RemoveEnvDraft'](arg1);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['storage']['DesktopStorage']['RenameCollection'](arg1, arg2);
}

export function SaveDraftAsRequest(arg1, arg2) {
  return window['go']['storage']['DesktopStorage']['SaveDraftAsRequest'](arg1, arg2);
}

export function SaveEnvDraftAsEnv(arg1, arg2) {
  return window['go']['storage']['DesktopStorage']['SaveEnvDraftAsEnv'](arg1, arg2);
}

export function SaveMockDraftAsMock(arg1, arg2) {
  return window['go']['storage']['DesktopStorage']['SaveMockDraftAsMock'](arg1, arg2);
}

export function SaveRequestCopy(arg1, arg2) {
  return window['go']['storage']['DesktopStorage']['SaveRequestCopy'](arg1, arg2);
}

export function UpdateDraftFields(arg1, arg2) {
  return window['go']['storage']['DesktopStorage']['UpdateDraftFields'](arg1, arg2);
}

export function UpdateEnvDraftData(arg1, arg2) {
  return window['go']['storage']['DesktopStorage']['UpdateEnvDraftData'](arg1, arg2);
}

export function UpdateMockDraftFields(arg1, arg2) {
  return window['go']['storage']['DesktopStorage']['UpdateMockDraftFields'](arg1, arg2);
}

export function UpdateMockServer(arg1, arg2) {
  return window['go']['storage']['DesktopStorage']['UpdateMockServer'](arg1, arg2);
}

export function UpdateUIState(arg1) {
  return window['go']['storage']['DesktopStorage']['UpdateUIState'](arg1);
}

export function UpdateWorkspace(arg1, arg2) {
  return window['go']['storage']['DesktopStorage']['UpdateWorkspace'](arg1, arg2);
}
