// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddCollection(arg1:models.CreateCollectionDTO):Promise<void>;

export function AddDraft(arg1:models.RequestDraftDTO):Promise<void>;

export function AddDraftFromRequest(arg1:string,arg2:models.AddDraftDTO):Promise<void>;

export function AddEnvironment(arg1:models.AddEnvironmentDTO):Promise<void>;

export function AddEnvironmentDraft(arg1:models.AddEnvironmentDraftDTO):Promise<void>;

export function AddFreshDraft(arg1:models.AddDraftDTO):Promise<void>;

export function AddFreshEnvDraft(arg1:string):Promise<void>;

export function AddReqExample(arg1:models.ReqExampleDTO,arg2:models.SavedResponseRenderMeta):Promise<void>;

export function ChooseFile():Promise<models.FileStats>;

export function ClearCollection(arg1:string):Promise<void>;

export function CopyEnvironment(arg1:string,arg2:models.CopyEnvironmentDTO):Promise<void>;

export function CreateWorkspace(arg1:models.CreateWorkspaceDTO):Promise<void>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteDraftsUnderCollection(arg1:string):Promise<void>;

export function DeleteEnvDraftsUnderEnv(arg1:string):Promise<void>;

export function DeleteReqExample(arg1:string):Promise<void>;

export function DeleteRequestDrafts(arg1:string):Promise<void>;

export function DeleteSavedReq(arg1:string):Promise<void>;

export function FindDraftById(arg1:string):Promise<models.RequestDraftDTO>;

export function FindEnvDraft(arg1:string):Promise<models.EnvironmentDraftDTO>;

export function GetAllCollections(arg1:string):Promise<Array<models.CollectionDTO>>;

export function GetAllWorkspaces():Promise<Array<models.WorkspaceLightDTO>>;

export function GetEnvironments(arg1:string):Promise<Array<models.EnvironmentDTO>>;

export function GetReqExampleById(arg1:string):Promise<models.ReqExampleDTO>;

export function GetReqExamples(arg1:string):Promise<Array<models.ReqExampleLightDTO>>;

export function GetSavedRequests(arg1:string):Promise<Array<models.RequestLightDTO>>;

export function GetUIState():Promise<models.UIStateDTO>;

export function GetWorkspaceById(arg1:string):Promise<models.WorkspaceDTO>;

export function RemoveDraft(arg1:string):Promise<void>;

export function RemoveEnv(arg1:string):Promise<void>;

export function RemoveEnvDraft(arg1:string):Promise<void>;

export function RenameCollection(arg1:string,arg2:string):Promise<void>;

export function SaveDraftAsRequest(arg1:string,arg2:models.SaveDraftAsReqDTO):Promise<void>;

export function SaveEnvDraftAsEnv(arg1:string,arg2:models.SaveEnvDraftAsEnvDTO):Promise<void>;

export function SaveFile(arg1:models.DownloadTmpFileDTO):Promise<void>;

export function SaveRequestCopy(arg1:string,arg2:models.SaveRequestCopyDTO):Promise<void>;

export function UpdateDraftFields(arg1:string,arg2:models.UpdateDraftFieldsDTO):Promise<void>;

export function UpdateEnvDraftData(arg1:string,arg2:models.UpdateEnvDraftDataDTO):Promise<void>;

export function UpdateUIState(arg1:models.UpdateUIStateDTO):Promise<void>;

export function UpdateWorkspace(arg1:string,arg2:models.UpdateWorkspaceDTO):Promise<void>;
