// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddCollection(arg1:models.AddCollectionDTO):Promise<void>;

export function AddDraft(arg1:models.RequestDraftDTO):Promise<void>;

export function AddDraftFromRequest(arg1:models.AddDraftFromRequestDTO):Promise<void>;

export function AddEnvironment(arg1:models.AddEnvironmentDTO):Promise<void>;

export function AddEnvironmentDraft(arg1:models.AddEnvironmentDraftDTO):Promise<void>;

export function AddFreshDraft(arg1:models.AddFreshDraftDTO):Promise<void>;

export function AddFreshEnvDraft(arg1:string):Promise<void>;

export function AddReqExample(arg1:models.ReqExampleDTO,arg2:models.SavedResponseRenderMeta):Promise<void>;

export function ChooseFile():Promise<models.FileStats>;

export function ClearCollection(arg1:string):Promise<void>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteDraftsUnderCollection(arg1:string):Promise<void>;

export function DeleteEnvDraftsUnderEnv(arg1:string):Promise<void>;

export function DeleteReqExample(arg1:string):Promise<void>;

export function DeleteRequestDrafts(arg1:string):Promise<void>;

export function DeleteSavedReq(arg1:string):Promise<void>;

export function FindDraftById(arg1:string):Promise<models.RequestDraftDTO>;

export function FindDraftIdsByCollection(arg1:string):Promise<Array<string>>;

export function FindEnvDraft(arg1:string):Promise<models.EnvironmentDraftDTO>;

export function GetAllCollections():Promise<Array<models.CollectionDTO>>;

export function GetEnvironments():Promise<Array<models.EnvironmentDTO>>;

export function GetReqExampleById(arg1:string):Promise<models.ReqExampleDTO>;

export function GetReqExamples():Promise<Array<models.ReqExampleLightDTO>>;

export function GetSavedRequests():Promise<Array<models.RequestLightDTO>>;

export function GetUIState():Promise<models.UIStateDTO>;

export function RemoveDraft(arg1:string):Promise<void>;

export function RemoveEnv(arg1:string):Promise<void>;

export function RemoveEnvDraft(arg1:string):Promise<void>;

export function RenameCollection(arg1:string,arg2:string):Promise<void>;

export function SaveDraftAsRequest(arg1:models.SaveDraftAsReqDTO):Promise<void>;

export function SaveEnvDraftAsEnv(arg1:models.SaveEnvDraftAsEnvDTO):Promise<void>;

export function SaveFile(arg1:string):Promise<void>;

export function SaveRequestCopy(arg1:models.SaveRequestCopyDTO):Promise<void>;

export function UpdateActiveTab(arg1:string):Promise<void>;

export function UpdateAlwaysDiscardDraftsPreference(arg1:boolean):Promise<void>;

export function UpdateAlwaysDiscardEnvDraftsPreference(arg1:boolean):Promise<void>;

export function UpdateDraftApiKeyAuth(arg1:models.UpdateDraftApiKeyAuthDTO):Promise<void>;

export function UpdateDraftAuthEnabled(arg1:models.UpdateDraftAuthEnabledDTO):Promise<void>;

export function UpdateDraftAuthType(arg1:models.UpdateDraftAuthTypeDTO):Promise<void>;

export function UpdateDraftBasicAuth(arg1:models.UpdateDraftBasicAuthDTO):Promise<void>;

export function UpdateDraftBinaryBody(arg1:models.UpdateDraftBinaryBodyDTO):Promise<void>;

export function UpdateDraftBodyType(arg1:models.UpdateDraftBodyTypeDTO):Promise<void>;

export function UpdateDraftCookies(arg1:models.UpdateDraftCookiesDTO):Promise<void>;

export function UpdateDraftHeaders(arg1:models.UpdateDraftHeadersDTO):Promise<void>;

export function UpdateDraftMethod(arg1:models.UpdateDraftMethodDTO):Promise<void>;

export function UpdateDraftMultipartForm(arg1:models.UpdateDraftMultipartFormDTO):Promise<void>;

export function UpdateDraftQuery(arg1:models.UpdateDraftQueryDTO):Promise<void>;

export function UpdateDraftTextBody(arg1:models.UpdateDraftTextBodyDTO):Promise<void>;

export function UpdateDraftTokenAuth(arg1:models.UpdateDraftTokenAuthDTO):Promise<void>;

export function UpdateDraftUrl(arg1:models.UpdateDraftUrlDTO):Promise<void>;

export function UpdateDraftUrlEncodedForm(arg1:models.UpdateDraftUrlEncodedFormDTO):Promise<void>;

export function UpdateEnvDraftData(arg1:models.UpdateEnvDraftDataDTO):Promise<void>;

export function UpdateLayoutPreference(arg1:string):Promise<void>;

export function UpdateOpenTabs(arg1:models.UpdateOpenTabsDTO):Promise<void>;

export function UpdateSideBarPreference(arg1:boolean):Promise<void>;
