// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCollection(arg1) {
  return window['go']['storage']['Storage']['AddCollection'](arg1);
}

export function AddDraft(arg1) {
  return window['go']['storage']['Storage']['AddDraft'](arg1);
}

export function AddFreshDraft(arg1) {
  return window['go']['storage']['Storage']['AddFreshDraft'](arg1);
}

export function ChooseFile() {
  return window['go']['storage']['Storage']['ChooseFile']();
}

export function ClearCollection(arg1) {
  return window['go']['storage']['Storage']['ClearCollection'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['storage']['Storage']['DeleteCollection'](arg1);
}

export function DeleteDraftsUnderCollection(arg1) {
  return window['go']['storage']['Storage']['DeleteDraftsUnderCollection'](arg1);
}

export function DeleteRequestDrafts(arg1) {
  return window['go']['storage']['Storage']['DeleteRequestDrafts'](arg1);
}

export function DeleteSavedReq(arg1) {
  return window['go']['storage']['Storage']['DeleteSavedReq'](arg1);
}

export function FindDraftById(arg1) {
  return window['go']['storage']['Storage']['FindDraftById'](arg1);
}

export function FindDraftIdsByCollection(arg1) {
  return window['go']['storage']['Storage']['FindDraftIdsByCollection'](arg1);
}

export function GetAllCollections() {
  return window['go']['storage']['Storage']['GetAllCollections']();
}

export function GetSavedRequests() {
  return window['go']['storage']['Storage']['GetSavedRequests']();
}

export function GetUIState() {
  return window['go']['storage']['Storage']['GetUIState']();
}

export function RemoveDraft(arg1) {
  return window['go']['storage']['Storage']['RemoveDraft'](arg1);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['storage']['Storage']['RenameCollection'](arg1, arg2);
}

export function SaveDraftAsRequest(arg1) {
  return window['go']['storage']['Storage']['SaveDraftAsRequest'](arg1);
}

export function SaveFile(arg1) {
  return window['go']['storage']['Storage']['SaveFile'](arg1);
}

export function SaveRequestCopy(arg1) {
  return window['go']['storage']['Storage']['SaveRequestCopy'](arg1);
}

export function UpdateActiveTab(arg1) {
  return window['go']['storage']['Storage']['UpdateActiveTab'](arg1);
}

export function UpdateAlwaysDiscardDraftsPreference(arg1) {
  return window['go']['storage']['Storage']['UpdateAlwaysDiscardDraftsPreference'](arg1);
}

export function UpdateDraftApiKeyAuth(arg1) {
  return window['go']['storage']['Storage']['UpdateDraftApiKeyAuth'](arg1);
}

export function UpdateDraftAuthEnabled(arg1) {
  return window['go']['storage']['Storage']['UpdateDraftAuthEnabled'](arg1);
}

export function UpdateDraftAuthType(arg1) {
  return window['go']['storage']['Storage']['UpdateDraftAuthType'](arg1);
}

export function UpdateDraftBasicAuth(arg1) {
  return window['go']['storage']['Storage']['UpdateDraftBasicAuth'](arg1);
}

export function UpdateDraftBinaryBody(arg1) {
  return window['go']['storage']['Storage']['UpdateDraftBinaryBody'](arg1);
}

export function UpdateDraftBodyType(arg1) {
  return window['go']['storage']['Storage']['UpdateDraftBodyType'](arg1);
}

export function UpdateDraftCookies(arg1) {
  return window['go']['storage']['Storage']['UpdateDraftCookies'](arg1);
}

export function UpdateDraftHeaders(arg1) {
  return window['go']['storage']['Storage']['UpdateDraftHeaders'](arg1);
}

export function UpdateDraftMethod(arg1) {
  return window['go']['storage']['Storage']['UpdateDraftMethod'](arg1);
}

export function UpdateDraftMultipartForm(arg1) {
  return window['go']['storage']['Storage']['UpdateDraftMultipartForm'](arg1);
}

export function UpdateDraftQuery(arg1) {
  return window['go']['storage']['Storage']['UpdateDraftQuery'](arg1);
}

export function UpdateDraftTextBody(arg1) {
  return window['go']['storage']['Storage']['UpdateDraftTextBody'](arg1);
}

export function UpdateDraftTokenAuth(arg1) {
  return window['go']['storage']['Storage']['UpdateDraftTokenAuth'](arg1);
}

export function UpdateDraftUrl(arg1) {
  return window['go']['storage']['Storage']['UpdateDraftUrl'](arg1);
}

export function UpdateDraftUrlEncodedForm(arg1) {
  return window['go']['storage']['Storage']['UpdateDraftUrlEncodedForm'](arg1);
}

export function UpdateLayoutPreference(arg1) {
  return window['go']['storage']['Storage']['UpdateLayoutPreference'](arg1);
}

export function UpdateOpenTabs(arg1) {
  return window['go']['storage']['Storage']['UpdateOpenTabs'](arg1);
}

export function UpdateSideBarPreference(arg1) {
  return window['go']['storage']['Storage']['UpdateSideBarPreference'](arg1);
}
