// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCollection(arg1) {
  return window['go']['storage']['Storage']['AddCollection'](arg1);
}

export function AddDraft(arg1) {
  return window['go']['storage']['Storage']['AddDraft'](arg1);
}

export function AddDraftFromRequest(arg1) {
  return window['go']['storage']['Storage']['AddDraftFromRequest'](arg1);
}

export function AddEnvironment(arg1) {
  return window['go']['storage']['Storage']['AddEnvironment'](arg1);
}

export function AddEnvironmentDraft(arg1) {
  return window['go']['storage']['Storage']['AddEnvironmentDraft'](arg1);
}

export function AddFreshDraft(arg1) {
  return window['go']['storage']['Storage']['AddFreshDraft'](arg1);
}

export function AddFreshEnvDraft(arg1) {
  return window['go']['storage']['Storage']['AddFreshEnvDraft'](arg1);
}

export function AddReqExample(arg1, arg2) {
  return window['go']['storage']['Storage']['AddReqExample'](arg1, arg2);
}

export function ChooseFile() {
  return window['go']['storage']['Storage']['ChooseFile']();
}

export function ClearCollection(arg1) {
  return window['go']['storage']['Storage']['ClearCollection'](arg1);
}

export function CopyEnvironment(arg1) {
  return window['go']['storage']['Storage']['CopyEnvironment'](arg1);
}

export function CreateWorkspace(arg1) {
  return window['go']['storage']['Storage']['CreateWorkspace'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['storage']['Storage']['DeleteCollection'](arg1);
}

export function DeleteDraftsUnderCollection(arg1) {
  return window['go']['storage']['Storage']['DeleteDraftsUnderCollection'](arg1);
}

export function DeleteEnvDraftsUnderEnv(arg1) {
  return window['go']['storage']['Storage']['DeleteEnvDraftsUnderEnv'](arg1);
}

export function DeleteReqExample(arg1) {
  return window['go']['storage']['Storage']['DeleteReqExample'](arg1);
}

export function DeleteRequestDrafts(arg1) {
  return window['go']['storage']['Storage']['DeleteRequestDrafts'](arg1);
}

export function DeleteSavedReq(arg1) {
  return window['go']['storage']['Storage']['DeleteSavedReq'](arg1);
}

export function FindDraftById(arg1) {
  return window['go']['storage']['Storage']['FindDraftById'](arg1);
}

export function FindDraftIdsByCollection(arg1) {
  return window['go']['storage']['Storage']['FindDraftIdsByCollection'](arg1);
}

export function FindEnvDraft(arg1) {
  return window['go']['storage']['Storage']['FindEnvDraft'](arg1);
}

export function GetAllCollections(arg1) {
  return window['go']['storage']['Storage']['GetAllCollections'](arg1);
}

export function GetAllWorkspaces() {
  return window['go']['storage']['Storage']['GetAllWorkspaces']();
}

export function GetEnvironments(arg1) {
  return window['go']['storage']['Storage']['GetEnvironments'](arg1);
}

export function GetReqExampleById(arg1) {
  return window['go']['storage']['Storage']['GetReqExampleById'](arg1);
}

export function GetReqExamples(arg1) {
  return window['go']['storage']['Storage']['GetReqExamples'](arg1);
}

export function GetSavedRequests(arg1) {
  return window['go']['storage']['Storage']['GetSavedRequests'](arg1);
}

export function GetUIState() {
  return window['go']['storage']['Storage']['GetUIState']();
}

export function GetWorkspaceById(arg1) {
  return window['go']['storage']['Storage']['GetWorkspaceById'](arg1);
}

export function RemoveDraft(arg1) {
  return window['go']['storage']['Storage']['RemoveDraft'](arg1);
}

export function RemoveEnv(arg1) {
  return window['go']['storage']['Storage']['RemoveEnv'](arg1);
}

export function RemoveEnvDraft(arg1) {
  return window['go']['storage']['Storage']['RemoveEnvDraft'](arg1);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['storage']['Storage']['RenameCollection'](arg1, arg2);
}

export function SaveDraftAsRequest(arg1) {
  return window['go']['storage']['Storage']['SaveDraftAsRequest'](arg1);
}

export function SaveEnvDraftAsEnv(arg1) {
  return window['go']['storage']['Storage']['SaveEnvDraftAsEnv'](arg1);
}

export function SaveFile(arg1) {
  return window['go']['storage']['Storage']['SaveFile'](arg1);
}

export function SaveRequestCopy(arg1) {
  return window['go']['storage']['Storage']['SaveRequestCopy'](arg1);
}

export function UpdateDraftFields(arg1) {
  return window['go']['storage']['Storage']['UpdateDraftFields'](arg1);
}

export function UpdateEnvDraftData(arg1) {
  return window['go']['storage']['Storage']['UpdateEnvDraftData'](arg1);
}

export function UpdateUIState(arg1) {
  return window['go']['storage']['Storage']['UpdateUIState'](arg1);
}

export function UpdateWorkspace(arg1, arg2) {
  return window['go']['storage']['Storage']['UpdateWorkspace'](arg1, arg2);
}
