version: '3'

services:
  gurl:
    container_name: gurl-web-container
    image: gurl-web
    env_file:
      - ./web/web.env.prod
    build: .
    restart: unless-stopped
    volumes:
      - ./appData:/usr/local/src/gURL
    ports:
      - "8080:80"