version: '3'

services:
  db:
    container_name: gurl-web-db
    image: ${POSTGRES_IMAGE}
    volumes:
      - gurl-web-db-volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env.local
    networks:
      - gurl-web-prod-network
  gurl:
    depends_on:
      - db
    container_name: gurl-web-container
    image: gurl-web 
    build: .
    env_file:
      - public.env.prod
    networks:
      -  gurl-web-prod-network
    volumes:
      - ./appData:/usr/local/src/gURL
      
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    depends_on:
      - gurl
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      -  gurl-web-prod-network

volumes:
  gurl-web-db-volume:
    driver: local

networks:
  gurl-web-prod-network:
    driver: bridge