// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportCollection(arg1) {
  return window['go']['exporter']['DesktopExporter']['ExportCollection'](arg1);
}

export function ExportEnvironment(arg1) {
  return window['go']['exporter']['DesktopExporter']['ExportEnvironment'](arg1);
}

export function ImportCollection(arg1) {
  return window['go']['exporter']['DesktopExporter']['ImportCollection'](arg1);
}

export function ImportEnvironment(arg1) {
  return window['go']['exporter']['DesktopExporter']['ImportEnvironment'](arg1);
}
