// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportCollection(arg1:string):Promise<void>;

export function ExportEnvironment(arg1:string):Promise<void>;

export function ImportCollection():Promise<void>;

export function ImportEnvironment():Promise<void>;
