// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportCollection(arg1) {
  return window['go']['exporter']['Exporter']['ExportCollection'](arg1);
}

export function ExportEnvironment(arg1) {
  return window['go']['exporter']['Exporter']['ExportEnvironment'](arg1);
}

export function ImportCollection() {
  return window['go']['exporter']['Exporter']['ImportCollection']();
}

export function ImportEnvironment() {
  return window['go']['exporter']['Exporter']['ImportEnvironment']();
}
