// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelReq(arg1) {
  return window['go']['executor']['Executor']['CancelReq'](arg1);
}

export function ParseCookieRaw(arg1) {
  return window['go']['executor']['Executor']['ParseCookieRaw'](arg1);
}

export function SendHttpReq(arg1) {
  return window['go']['executor']['Executor']['SendHttpReq'](arg1);
}
