// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CancelReq(arg1:string):Promise<void>;

export function ParseCookieRaw(arg1:string):Promise<Array<models.GurlKeyValItem>>;

export function SendHttpReq(arg1:models.GurlReq):Promise<models.GurlRes>;
