// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCollection(arg1) {
  return window['go']['main']['Gurl']['AddCollection'](arg1);
}

export function AddDraft(arg1) {
  return window['go']['main']['Gurl']['AddDraft'](arg1);
}

export function AddFreshDraft(arg1) {
  return window['go']['main']['Gurl']['AddFreshDraft'](arg1);
}

export function CancelReq(arg1) {
  return window['go']['main']['Gurl']['CancelReq'](arg1);
}

export function ChooseFile() {
  return window['go']['main']['Gurl']['ChooseFile']();
}

export function FindDraftById(arg1) {
  return window['go']['main']['Gurl']['FindDraftById'](arg1);
}

export function GetAllCollections() {
  return window['go']['main']['Gurl']['GetAllCollections']();
}

export function GetOpenTabs() {
  return window['go']['main']['Gurl']['GetOpenTabs']();
}

export function GetSavedRequests() {
  return window['go']['main']['Gurl']['GetSavedRequests']();
}

export function ReadFileText(arg1) {
  return window['go']['main']['Gurl']['ReadFileText'](arg1);
}

export function RemoveDraft(arg1) {
  return window['go']['main']['Gurl']['RemoveDraft'](arg1);
}

export function SaveDraftAsRequest(arg1) {
  return window['go']['main']['Gurl']['SaveDraftAsRequest'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['Gurl']['SaveFile'](arg1, arg2);
}

export function SendReq(arg1) {
  return window['go']['main']['Gurl']['SendReq'](arg1);
}

export function UpdateDraftBinaryBody(arg1) {
  return window['go']['main']['Gurl']['UpdateDraftBinaryBody'](arg1);
}

export function UpdateDraftBodyType(arg1) {
  return window['go']['main']['Gurl']['UpdateDraftBodyType'](arg1);
}

export function UpdateDraftHeaders(arg1) {
  return window['go']['main']['Gurl']['UpdateDraftHeaders'](arg1);
}

export function UpdateDraftMethod(arg1) {
  return window['go']['main']['Gurl']['UpdateDraftMethod'](arg1);
}

export function UpdateDraftMultipartForm(arg1) {
  return window['go']['main']['Gurl']['UpdateDraftMultipartForm'](arg1);
}

export function UpdateDraftQuery(arg1) {
  return window['go']['main']['Gurl']['UpdateDraftQuery'](arg1);
}

export function UpdateDraftTextBody(arg1) {
  return window['go']['main']['Gurl']['UpdateDraftTextBody'](arg1);
}

export function UpdateDraftUrl(arg1) {
  return window['go']['main']['Gurl']['UpdateDraftUrl'](arg1);
}

export function UpdateDraftUrlEncodedForm(arg1) {
  return window['go']['main']['Gurl']['UpdateDraftUrlEncodedForm'](arg1);
}

export function UpdateOpenTabs(arg1) {
  return window['go']['main']['Gurl']['UpdateOpenTabs'](arg1);
}
