// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelReq(arg1) {
  return window['go']['main']['Gurl']['CancelReq'](arg1);
}

export function ChooseFile() {
  return window['go']['main']['Gurl']['ChooseFile']();
}

export function SendReq(arg1) {
  return window['go']['main']['Gurl']['SendReq'](arg1);
}
