// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddCollection(arg1:models.AddCollectionDTO):Promise<void>;

export function AddDraft(arg1:models.RequestDraftDTO):Promise<void>;

export function AddFreshDraft(arg1:models.AddFreshDraftDTO):Promise<void>;

export function CancelReq(arg1:string):Promise<void>;

export function ChooseFile():Promise<models.FileStats>;

export function FindDraftById(arg1:string):Promise<models.RequestDraftDTO>;

export function GetAllCollections():Promise<Array<models.CollectionDTO>>;

export function GetOpenTabs():Promise<string>;

export function GetSavedRequests():Promise<Array<models.RequestDTO>>;

export function ReadFileText(arg1:string):Promise<string>;

export function RemoveDraft(arg1:string):Promise<void>;

export function SaveDraftAsRequest(arg1:models.SaveDraftAsReqDTO):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SendReq(arg1:models.GurlReq):Promise<models.GurlRes>;

export function UpdateDraftBinaryBody(arg1:models.UpdateDraftBinaryBodyDTO):Promise<void>;

export function UpdateDraftBodyType(arg1:models.UpdateDraftBodyTypeDTO):Promise<void>;

export function UpdateDraftHeaders(arg1:models.UpdateDraftHeadersDTO):Promise<void>;

export function UpdateDraftMethod(arg1:models.UpdateDraftMethodDTO):Promise<void>;

export function UpdateDraftMultipartForm(arg1:models.UpdateDraftMultipartFormDTO):Promise<void>;

export function UpdateDraftQuery(arg1:models.UpdateDraftQueryDTO):Promise<void>;

export function UpdateDraftTextBody(arg1:models.UpdateDraftTextBodyDTO):Promise<void>;

export function UpdateDraftUrl(arg1:models.UpdateDraftUrlDTO):Promise<void>;

export function UpdateDraftUrlEncodedForm(arg1:models.UpdateDraftUrlEncodedFormDTO):Promise<void>;

export function UpdateOpenTabs(arg1:models.UpdateOpenTabsDTO):Promise<void>;
