// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelReq(arg1:string):Promise<void>;

export function ChooseFile():Promise<main.FileStats>;

export function SendReq(arg1:main.GurlReq):Promise<main.GurlRes>;
